"""
Configuration constants for the behavioral authentication engine.
"""

# Vector dimensions
TYPING_FEATURES_DIM = 25
TOUCH_FEATURES_DIM = 30
NAVIGATION_FEATURES_DIM = 20
CONTEXTUAL_FEATURES_DIM = 15
TOTAL_VECTOR_DIM = TYPING_FEATURES_DIM + TOUCH_FEATURES_DIM + NAVIGATION_FEATURES_DIM + CONTEXTUAL_FEATURES_DIM

# Learning phases
LEARNING_PHASE_SESSIONS = 3
GRADUAL_RISK_SESSIONS = 10
FULL_AUTH_SESSIONS = 11

# Risk thresholds
NEW_USER_RISK_THRESHOLD = 0.8
MODERATE_USER_RISK_THRESHOLD = 0.6
EXPERIENCED_USER_RISK_THRESHOLD = 0.4

# Session thresholds
MODERATE_USER_SESSION_COUNT = 5
EXPERIENCED_USER_SESSION_COUNT = 20

# Performance targets (in milliseconds)
FAISS_RESPONSE_TIME_TARGET = 5
TRANSFORMER_RESPONSE_TIME_TARGET = 100
VECTOR_STORAGE_TIME_TARGET = 10

# API Configuration
DEFAULT_API_HOST = "0.0.0.0"
DEFAULT_API_PORT = 8001
DEFAULT_API_PREFIX = "/api/v1"

# Security
DEFAULT_ALGORITHM = "HS256"
DEFAULT_TOKEN_EXPIRE_MINUTES = 30

# ML Configuration
DEFAULT_BATCH_SIZE = 32
DEFAULT_MODEL_UPDATE_INTERVAL = 3600  # seconds
DEFAULT_FAISS_INDEX_TYPE = "IndexFlatIP"

# Storage
DEFAULT_HDF5_CHUNK_SIZE = 1000
DEFAULT_MAX_CONCURRENT_USERS = 1000
DEFAULT_RATE_LIMIT_PER_MINUTE = 60
DEFAULT_REQUEST_TIMEOUT = 30

# Feature extraction windows
TYPING_WINDOW_SIZE = 10  # keystrokes
TOUCH_WINDOW_SIZE = 5   # touch events
NAVIGATION_WINDOW_SIZE = 3  # navigation events

# Behavioral patterns
MIN_PATTERN_CONFIDENCE = 0.7
DRIFT_DETECTION_THRESHOLD = 0.3
ANOMALY_SCORE_THRESHOLD = 0.8
