version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - ml-engine
    restart: unless-stopped
    # Add volumes or extra config as needed
  ml-engine:
    build: ./ml-engine
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: unless-stopped
    # Add volumes or extra config as needed
# Add other services (e.g., dashboard) as needed 