name: canara_ai
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  hugeicons: ^0.0.11
  flutter_svg: ^2.2.0
  flutter_secure_storage: ^9.2.4
  flutter_tts: ^4.2.3
  path_provider: ^2.1.5
  uuid : ^4.5.1
  dio: ^5.8.0+1
  device_info_plus: ^11.3.0
  web_socket_channel: ^3.0.3 
  sensors_plus: ^6.1.1
  screen_brightness: ^2.1.5
  connectivity_plus: ^6.1.4
  package_info_plus: ^8.3.0
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
